PHQ9_X4_FEATURES = [
    "Agitation_Level",
    "Anhedonia_No_Joy",
    "Crying_Frequency",
    "Difficulty_Focusing",
    "Difficulty_Speaking_Socially",
    "Easy_Fatigue",
    "Emotional_Alignment_Frequency",
    "Fatigue_Frequency",
    "Fear_Something_Bad",
    "Feeling_Down",
    "Feeling_Insignificant",
    "Feels_Others_Are_Kind",
    "Feels_Pitied",
    "Financial_Pressure",
    "Future_Hopelessness",
    "Has_Debts",
    "High_Appetite",
    "Hopelessness_EndFeeling",
    "Indecisiveness",
    "Insomnia",
    "Interest_Loss",
    "Irritability",
    "Isolation_Frequency",
    "Lack_of_Pleasure",
    "Life_Feels_Hard",
    "Loneliness_Frequency",
    "Lost_Someone_Recently",
    "Low_Appetite",
    "Low_Concentration",
    "Meaninglessness",
    "Melancholic",
    "No_Support_Frequency",
    "On_Medication",
    "Performance_Decline",
    "Presence_Not_Genuine_Frequency",
    "Recent_Abuse_Experience",
    "Relationships_Unimportant_Level",
    "Restlessness",
    "Satisfied_Living_Environment",
    "Self_Confidence_Erosion",
    "Self_Perceived_Failure",
    "Share_Feelings_Lack",
    "Significant_Ailments",
    "Sleep_Duration",
    "Social Economic Status",
    "Social_LeftOut_Level",
    "Social_Media_Hours",
    "Social_Withdrawal",
    "Suicidal_Thoughts",
]
BDI_X1_FEATURES = [
    "Agitation_Level",
    "Anhedonia_No_Joy",
    "Crying_Frequency",
    "Difficulty_Focusing",
    "Easy_Fatigue",
    "Fatigue_Frequency",
    "Feeling_Insignificant",
    "Future_Hopelessness",
    "Hopelessness_EndFeeling",
    "Indecisiveness",
    "Insomnia",
    "Interest_Loss",
    "Irritability",
    "Low_Appetite",
    "Meaninglessness",
    "Melancholic",
    "Self_Confidence_Erosion",
    "Self_Perceived_Failure",
    "Social_Withdrawal",
    "Suicidal_Thoughts",
]
CESD_X3_FEATURES = [
    "Academic Status",
    "Age",
    "Agitation_Level",
    "Alcohol_Consumption",
    "Anhedonia_No_Joy",
    "Crying_Frequency",
    "Difficulty_Focusing",
    "Difficulty_Speaking_Socially",
    "Easy_Fatigue",
    "Emotional_Alignment_Frequency",
    "Fatigue_Frequency",
    "Fear_Something_Bad",
    "Feeling_Down",
    "Feeling_Insignificant",
    "Feels_Others_Are_Kind",
    "Feels_Pitied",
    "Financial_Pressure",
    "Future_Hopelessness",
    "Gender",
    "Has_Debts",
    "High_Appetite",
    "Hopelessness_EndFeeling",
    "Indecisiveness",
    "Insomnia",
    "Interest_Loss",
    "Irritability",
    "Isolation_Frequency",
    "Lack_of_Pleasure",
    "Life_Feels_Hard",
    "Loneliness_Frequency",
    "Lost_Someone_Recently",
    "Low_Appetite",
    "Low_Concentration",
    "Meaninglessness",
    "Melancholic",
    "No_Support_Frequency",
    "On_Medication",
    "Performance_Decline",
    "Physical_Activity",
    "Presence_Not_Genuine_Frequency",
    "Recent_Abuse_Experience",
    "Relationship_Status_Divorced",
    "Relationship_Status_In a Relationship",
    "Relationship_Status_Married",
    "Relationship_Status_Single",
    "Relationships_Unimportant_Level",
    "Residential_Area_Hall",
    "Residential_Area_Outside Hall",
    "Residential_Area_With family",
    "Restlessness",
    "Satisfied_Living_Environment",
    "Self_Confidence_Erosion",
    "Self_Perceived_Failure",
    "Share_Feelings_Lack",
    "Significant_Ailments",
    "Sleep_Duration",
    "Smoking",
    "Social Economic Status",
    "Social_LeftOut_Level",
    "Social_Media_Hours",
    "Social_Withdrawal",
    "Suicidal_Thoughts",
    "Work_While_Study",
    "Workload_Academic_Demand",
]

MODEL_FEATURES = {
    "bdi": BDI_X1_FEATURES,
    "phq9": PHQ9_X4_FEATURES,
    "cesd": CESD_X3_FEATURES,
}

ALL_FEATURES = sorted(
    set(PHQ9_X4_FEATURES)
    | set(BDI_X1_FEATURES)
    | set(CESD_X3_FEATURES)
)

ALL_FEATURES_SET = set(ALL_FEATURES)

